language: scala

scala:
  - 2.13.1

jdk:
  - openjdk8

before_install:
  - git fetch --tags
  - git submodule update --init

stages:
  - name: test

jobs:
  include:
    - stage: test
      script: sbt clean test

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache
    - $HOME/.coursier
    - target/repos

notifications:
  email:
    on_success: never