addSbtPlugin("io.superflat" % "lagompb-plugin" % "0.5.0")
addSbtPlugin("com.dwijnand" % "sbt-dynver" % "4.0.0")
addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.7.3")
addSbtPlugin("org.scalameta" % "sbt-scalafmt" % "2.4.0")
addSbtPlugin("au.com.onegeek" %% "sbt-dotenv" % "2.1.192")
addSbtPlugin("com.tapad" % "sbt-docker-compose" % "1.0.35")
